on:
  push:
    branches:
      - main

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    name: Deploy web
    steps:
      - uses: actions/checkout@v3
      - uses: adamghill/build-docker-and-deploy-to-caprover@v1
        with:
          caprover-app-name: fediview-web
          github-token: ${{ secrets.GITHUB_TOKEN }}
          caprover-server-url: ${{ secrets.CAPROVER_SERVER_URL }}
          caprover-app-token: ${{ secrets.CAPROVER_WEB_APP_TOKEN }}
          docker-file-name: ./Dockerfile
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
  deploy_worker:
    runs-on: ubuntu-latest
    name: Deploy worker
    needs: deploy_web
    steps:
      - uses: actions/checkout@v3
      - uses: adamghill/build-docker-and-deploy-to-caprover@v1
        with:
          caprover-app-name: fediview-q2-worker
          github-token: ${{ secrets.GITHUB_TOKEN }}
          caprover-server-url: ${{ secrets.CAPROVER_SERVER_URL }}
          caprover-app-token: ${{ secrets.CAPROVER_WORKER_APP_TOKEN }}
          docker-file-name: ./Dockerfile-q2-worker
